//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGC.GMES.MES.Common.BizInfoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BizInfoService.IBizActorInfoServer")]
    public interface IBizActorInfoServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizActorInfoServer/GetServiceInfo", ReplyAction="http://tempuri.org/IBizActorInfoServer/GetServiceInfoResponse")]
        System.Data.DataSet GetServiceInfo(string serviceName, System.Data.DataSet ds, string sysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizActorInfoServer/GetServiceInfo", ReplyAction="http://tempuri.org/IBizActorInfoServer/GetServiceInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetServiceInfoAsync(string serviceName, System.Data.DataSet ds, string sysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizActorInfoServer/GetServiceInfoXml", ReplyAction="http://tempuri.org/IBizActorInfoServer/GetServiceInfoXmlResponse")]
        string GetServiceInfoXml(string serviceName, string ds, string sysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizActorInfoServer/GetServiceInfoXml", ReplyAction="http://tempuri.org/IBizActorInfoServer/GetServiceInfoXmlResponse")]
        System.Threading.Tasks.Task<string> GetServiceInfoXmlAsync(string serviceName, string ds, string sysid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBizActorInfoServerChannel : LGC.GMES.MES.Common.BizInfoService.IBizActorInfoServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizActorInfoServerClient : System.ServiceModel.ClientBase<LGC.GMES.MES.Common.BizInfoService.IBizActorInfoServer>, LGC.GMES.MES.Common.BizInfoService.IBizActorInfoServer {
        
        public BizActorInfoServerClient() {
        }
        
        public BizActorInfoServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizActorInfoServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizActorInfoServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizActorInfoServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetServiceInfo(string serviceName, System.Data.DataSet ds, string sysid) {
            return base.Channel.GetServiceInfo(serviceName, ds, sysid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetServiceInfoAsync(string serviceName, System.Data.DataSet ds, string sysid) {
            return base.Channel.GetServiceInfoAsync(serviceName, ds, sysid);
        }
        
        public string GetServiceInfoXml(string serviceName, string ds, string sysid) {
            return base.Channel.GetServiceInfoXml(serviceName, ds, sysid);
        }
        
        public System.Threading.Tasks.Task<string> GetServiceInfoXmlAsync(string serviceName, string ds, string sysid) {
            return base.Channel.GetServiceInfoXmlAsync(serviceName, ds, sysid);
        }
    }
}
